config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :attendances
  resources :employees

  resources :stores
  get 'store/:id/reports', to: 'stores#reports', as: 'store_reports'
  get 'store/:id/reports/attendance_by_day', to: 'stores#reports_att_by_day', as: 'store_reports_att_by_day'
  post 'store/:id/reports/attendance_by_day/date', to: 'stores#reports_att_by_day_date',
                                                   as: 'store_reports_att_by_day_date'
  get 'store/:id/reports/absence_by_month', to: 'stores#reports_abs_by_month', as: 'store_reports_abs_by_month'
  post 'store/:id/reports/absence_by_month/date', to: 'stores#reports_abs_by_month_date',
                                                  as: 'store_reports_abs_by_month_date'
  get 'store/:id/reports/average_time_by_month', to: 'stores#reports_avg_time_by_month',
                                                 as: 'store_reports_avg_time_by_month'
  post 'store/:id/reports/average_time_by_month/date', to: 'stores#reports_avg_time_by_month_date',
                                                       as: 'store_reports_avg_time_by_month_date'

  # Session routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  belongs_to :store
  has_many :attendances

  before_create :random_private_number

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :position, presence: true

  private

  def random_private_number
    self.private_number = rand(1000..9999)
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  before_action :require_admin
  before_action :set_employee, only: %i[show edit update destroy]

  def show; end

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @employee.update(employee_params)
      redirect_to @employee
    else
      render 'edit'
    end
  end

  def destroy
    @employee.destroy

    redirect_to @employee
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :position, :working,
                                     :store_id)
  end
end

app/helpers/employees_helper.rb
# frozen_string_literal: true

module EmployeesHelper
end

app/views/employees/edit.html.erb
<div class="m-5">
  <h1>Employees edit form</h1>

  <% if @employee.errors.any? %>
    <h2>The following errors preventing articles to being saved</h2>
    <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with(model: @employee, local: true) do |f| %>
    <p>
      <%= f.label :first_name %><br/>
      <%= f.text_field :first_name %>
    </p>

    <p>
      <%= f.label :last_name %><br/>
      <%= f.text_field :last_name %>
    </p>

    <p>
      <%= f.label :email %><br/>
      <%= f.email_field :email %>
    </p>

    <p>
      <%= f.label :position %><br/>
      <%= f.text_field :position %>
    </p>

    <p>
      <%= f.label :working %><br/>
      <%= f.select :working, ["true", "false"] %>
    </p>

    <p>
      <%= f.label :store_id %><br/>
      <%= f.number_field :store_id %>
    </p>

    <p>
      <%= f.submit "Edit employee" , class: 'btn btn-success my-3' %>
    </p>

    <p>
      <td><%= link_to 'Cancel and return to employee index', employees_path, class: 'btn btn-primary my-3' %></td>
    </p>

  <% end %>
</div>

app/views/employees/index.html.erb
<h1 class="my-3">Employee Index</h1>

<p>
  <%= link_to 'Add new employee', new_employee_path, class: 'btn btn-primary my-3' %>
</p>

<div class="card">
  <div class="card-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">First name</th>
          <th scope="col">Last name</th>
          <th scope="col">Email</th>
          <th scope="col">Position</th>
          <th scope="col">Private number</th>
          <th scope="col">Working</th>
          <th scope="col">Store ID</th>
          <th coolspan=2>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @employees.each do |employee| %>
           <tr>
            <th scope="row"><%= employee.id %></th>
            <td><%= employee.first_name %></td>
            <td><%= employee.last_name %></td>
            <td><%= employee.email %></td>
            <td><%= employee.position %></td>
            <td><%= employee.private_number %></td>
            <td><%= employee.working %></td>
            <td><%= employee.store_id %></td>
            <td><%= link_to 'Show', employee_path(employee.id), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Edit', edit_employee_path(employee.id), class: 'btn btn-success' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/employees/new.html.erb
<div class="m-5">
  <h1>Employees new form</h1>

  <% if @employee.errors.any? %>
    <h2>The following errors preventing articles to being saved</h2>
    <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with scope: :employee, url: employees_path, local: true do |f| %>
    <p>
      <%= f.label :first_name %><br/>
      <%= f.text_field :first_name %>
    </p>

    <p>
      <%= f.label :last_name %><br/>
      <%= f.text_field :last_name %>
    </p>

    <p>
      <%= f.label :email %><br/>
      <%= f.email_field :email %>
    </p>

    <p>
      <%= f.label :position %><br/>
      <%= f.text_field :position %>
    </p>

    <p>
      <%= f.label :working %><br/>
      <%= f.select :working, ["true", "false"]  %>
    </p>

    <p>
      <%= f.label :store_id %><br/>
      <%= f.number_field :store_id %>
    </p>

    <p>
      <%= f.submit "Create new employee", class: 'btn btn-success my-3'%>
    </p>

    <p>
      <td><%= link_to 'Cancel and return to employee index', employees_path, class: 'btn btn-primary my-3' %></td>
    </p>

  <% end %>
</div>

app/views/employees/show.html.erb
<div class="m-5">
    <h1>Employees show employees</h1>

    <div class="card mt-5 p-1" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title mb-3">Employee ID: <%=@employee.id %></h5>
            <p>First name: <%= @employee.first_name %></p>
            <p>Last name: <%= @employee.last_name %></p>
            <p>Email: <%= @employee.email %></p>
            <p>Position: <%= @employee.position %></p>
            <p>Private number: <%= @employee.private_number %></p>
            <p>Working: <%= @employee.working %></p>
            <p>Store Id: <%= @employee.store_id %></p>
        </div>
    </div>

    <p>
      <td><%= link_to 'Return to employee index', employees_path, class: 'btn btn-primary my-3' %></td>
    </p>

</div>