config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :attendances
  resources :employees

  resources :stores
  get 'store/:id/reports', to: 'stores#reports', as: 'store_reports'
  get 'store/:id/reports/attendance_by_day', to: 'stores#reports_att_by_day', as: 'store_reports_att_by_day'
  post 'store/:id/reports/attendance_by_day/date', to: 'stores#reports_att_by_day_date',
                                                   as: 'store_reports_att_by_day_date'
  get 'store/:id/reports/absence_by_month', to: 'stores#reports_abs_by_month', as: 'store_reports_abs_by_month'
  post 'store/:id/reports/absence_by_month/date', to: 'stores#reports_abs_by_month_date',
                                                  as: 'store_reports_abs_by_month_date'
  get 'store/:id/reports/average_time_by_month', to: 'stores#reports_avg_time_by_month',
                                                 as: 'store_reports_avg_time_by_month'
  post 'store/:id/reports/average_time_by_month/date', to: 'stores#reports_avg_time_by_month_date',
                                                       as: 'store_reports_avg_time_by_month_date'

  # Session routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/store.rb
# frozen_string_literal: true

class Store < ApplicationRecord
  has_many :employees
  has_many :attendances

  validates :name, presence: true
  validates :address, presence: true
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

class StoresController < ApplicationController
  before_action :require_admin
  before_action :set_store,
                only: %i[show edit update destroy reports reports_att_by_day reports_att_by_day_date reports_abs_by_month
                         reports_abs_by_month_date reports_avg_time_by_month reports_avg_time_by_month_date]

  def show; end

  def index
    @stores = Store.all
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to @store
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @store.update(store_params)
      redirect_to @store
    else
      render 'edit'
    end
  end

  def destroy
    @store.destroy
    redirect_to stores_path
  end

  def reports; end

  def reports_att_by_day; end

  def reports_att_by_day_date
    date = params[:check_out].to_date
    date ? @reports = Attendance.where(check_out: date.all_day) : report_empty(:attendance)
  end

  def reports_abs_by_month; end

  def reports_abs_by_month_date
    return report_empty(:absence) if params[:month] == ''

    set_variables_for_reports
  end

  def reports_avg_time_by_month; end

  def reports_avg_time_by_month_date
    return report_empty(:average) if params[:month] == ''

    set_variables_for_reports
  end

  private

  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:name, :address)
  end

  def report_empty(type)
    flash[:alert] = 'Please select a date'
    return redirect_to store_reports_att_by_day_path if type == :attendance

    return redirect_to store_reports_abs_by_month_path if type == :absence

    redirect_to store_reports_avg_time_by_month_path if type == :average
  end

  def set_variables_for_reports
    date = "#{params[:month]}-01".to_date
    start_day = date
    end_day = date.end_of_month
    @working_days = start_day.business_days_until(end_day)
    @store_employees = @store.employees
    @attendance_by_month = Attendance.where(check_out: date.all_month)
  end
end

app/helpers/stores_helper.rb
# frozen_string_literal: true

module StoresHelper
end

app/views/stores/edit.html.erb
<div class="m-5">
  <h1>Stores edit form</h1>

  <% if @store.errors.any? %>
    <h2>The following errors preventing articles to being saved</h2>
    <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with(model: @store, local: true) do |f| %>
    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :address %><br/>
      <%= f.text_area :address %>
    </p>

    <p>
      <%= f.submit "Edit store", class: 'btn btn-success my-3'%>
    </p>

    <p>
      <td><%= link_to 'Cancel and return to store index', stores_path, class: 'btn btn-primary' %></td>
    </p>
  <% end %>
</div>

app/views/stores/index.html.erb
<h1 class="my-3">Store Index</h1>
<p>
  <%= link_to 'Add new stores', new_store_path, class: 'btn btn-primary my-3' %>
</p>

<div class="card">
  <div class="card-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Name</th>
          <th scope="col">Address</th>
          <th coolspan=3>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @stores.each do |store| %>
          <tr>
            <th scope="row"><%= store.id %></th>
            <td><%= store.name %></td>
            <td><%= store.address %></td>
            <td><%= link_to 'Show', store_path(store.id), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Edit', edit_store_path(store.id), class: 'btn btn-success' %></td>
            <td><%= link_to 'Reports', store_reports_path(store.id), class: 'btn btn-info' %></td>
            <td><%= link_to 'Delete', store_path(store), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/stores/new.html.erb
<div class= "m-5">
  <h1>Stores new form</h1>

  <% if @store.errors.any? %>
    <h2>The following errors preventing articles to being saved</h2>
    <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with scope: :store, url: stores_path, local: true do |f| %>
    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :address %><br/>
      <%= f.text_area :address %>
    </p>

    <p>
      <%= f.submit "Create new store", class: 'btn btn-success my-3'%>
    </p>

    <p>
      <td><%= link_to 'Cancel and return to store index', stores_path, class: 'btn btn-primary' %></td>
    </p>
  <% end %>
</div>

app/views/stores/reports.html.erb
<h1 class="mb-5"><%= @store.name %>'s reports</h1>
<div class="d-flex justify-content-evenly card">
	<div class="card-body">
    <table class="table table-striped">
			<thead>
					<tr>
						<th scope="col">Action</th>
						<th scope="col">Button</th>
					</tr>
			</thead>
			<tbody>
					<tr>
						<td scope="row">Attendance by day</td>
						<th scope="row"><%= link_to "Generate Report", store_reports_att_by_day_path(@store.id), class: 'btn btn-primary'  %></th>
					</tr>
					<tr>
						<td scope="row">Absence report by month</td>
						<th scope="row"><%= link_to "Generate Report", store_reports_abs_by_month_path(@store.id), class: 'btn btn-primary'  %></th>
					</tr>
					<tr>
						<td scope="row">Average time employees checked in/out by month</td>
						<th scope="row"><%= link_to "Generate Report", store_reports_avg_time_by_month_path(@store.id), class: 'btn btn-primary'  %></th>
					</tr>
			</tbody>
    </table>
	</div>
</div>
<p>
	<td><%= link_to 'Go back', stores_path, class: 'btn btn-secondary mt-5' %></td>
</p>

app/views/stores/reports_abs_by_month.html.erb
<h1><%= @store.name %></h1>
<%= form_with url: store_reports_abs_by_month_date_path do |f| %>
  <div class="card my-5">
    <div class="card-header">
      Absence by month
    </div>
    <div class="card-body">
      <table class="table table-striped">
        <thead>
            <tr>
              <th scope="col">Select Date</th>
              <th scope="col">Submit</th>
            </tr>
        </thead>
        <tbody>
            <tr>
              <td scope="row"><%= f.month_field :month %></td>
              <td scope="row"><%= f.submit "Generate report", class: 'btn btn-success my-3'%></td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
  <p>
    <td><%= link_to 'Cancel and return to reports index', store_reports_path, class: 'btn btn-primary' %></td>
  </p>
<% end %>

app/views/stores/reports_abs_by_month_date.html.erb
<h1><%= @store.name %> - Reports here</h1>
<h2><%= @working_days %> Working days </h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Employee id</th>
      <th scope="col">Employee name</th>
      <th scope="col">Absences</th>
      <th scope="col">Absences Porcentage</th>
    </tr>
  </thead>
  <tbody>
    <% @store_employees.each do |employee| %>
      <tr>
        <% assistance = Attendance.where(employee_id: employee.id).where.not(check_out: nil).length %>
        <% absences = @working_days - assistance %>
        <% absences_percentage = (absences * 100) / @working_days %>
        <th scope="row"><%= employee.id %></th>
        <th scope="row"><%= "#{employee.first_name} #{employee.last_name}" %></th>
        <th scope="row"><%= "#{ absences }" %></th>
        <th scope="row"><%= "#{ absences_percentage }%" %></th>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
  <td><%= link_to 'Cancel and return to reports index', store_reports_path, class: 'btn btn-primary' %></td>
</p>

app/views/stores/reports_att_by_day.html.erb
<h1><%= @store.name %></h1>
  <%= form_with url: store_reports_att_by_day_date_path do |f| %>
    <div class="card my-5">
      <div class="card-header">
        Attendance by day
      </div>
      <div class="card-body">
        <table class="table table-striped">
          <thead>
              <tr>
                <th scope="col">Select Date</th>
                <th scope="col">Submit</th>
              </tr>
          </thead>
          <tbody>
              <tr>
                <td scope="row"><%= f.date_field :check_out %></td>
                <td scope="row"><%= f.submit "Generate report", class: 'btn btn-success my-3'%></td>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
    <p>
      <td><%= link_to 'Cancel and return to reports index', store_reports_path, class: 'btn btn-primary' %></td>
    </p>
  <% end %>

app/views/stores/reports_att_by_day_date.html.erb
<h1><%= @store.name %> - Reports here</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Employee id</th>
      <th scope="col">Employee Name</th>
      <th scope="col">Check_in</th>
      <th scope="col">Check_out</th>
      <th scope="col">Show</th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <th scope="row"><%= report.employee_id %></th>
        <th scope="row"><%= Employee.find(report.employee_id).first_name + ' ' + Employee.find(report.employee_id).last_name %></th>
        <td><%= report.check_in %></td>
        <td><%= report.check_out %></td>
        <td><%= link_to 'Show', employee_path(Employee.find(report.employee_id)), class: 'btn btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
  <td><%= link_to 'Cancel and return to reports index', store_reports_path, class: 'btn btn-primary' %></td>
</p>

app/views/stores/reports_avg_time_by_month.html.erb
<h1><%= @store.name %></h1>
<%= form_with url: store_reports_avg_time_by_month_date_path do |f| %>
  <div class="card my-5">
    <div class="card-header">
      Average hours worked by month
    </div>
    <div class="card-body">
      <table class="table table-striped">
        <thead>
            <tr>
              <th scope="col">Select Date</th>
              <th scope="col">Submit</th>
            </tr>
        </thead>
        <tbody>
            <tr>
              <td scope="row"><%= f.month_field :month %></td>
              <td scope="row"><%= f.submit "Generate report", class: 'btn btn-success my-3'%></td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
  <p>
    <td><%= link_to 'Cancel and return to reports index', store_reports_path, class: 'btn btn-primary' %></td>
  </p>
<% end %>

app/views/stores/reports_avg_time_by_month_date.html.erb
<h1><%= @store.name %> - Reports here</h1>
<h2><%= @working_days %> Working days </h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Employee id</th>
      <th scope="col">Employee name</th>
      <th scope="col">Average hours worked</th>
      <th scope="col">Total hours worked</th>
      <th scope="col">Laboral hours of month</th>
    </tr>
  </thead>
  <tbody>
    <% @store_employees.each do |employee| %>
      <tr>
        <% assistance = Attendance.where(employee_id: employee.id).where.not(check_out: nil) %>
        <% total_hours= 0 %>
        <% assistance.each do |assist| %>
          <% total_hours += assist.check_out - assist.check_in %>
        <%end%>
        <% average_hours = total_hours/@working_days%>
        <% absences = @working_days - assistance.length %>
        <% absences_percentage = (absences * 100) / @working_days %>
        <% laboral_hours = 8 * @working_days %>
        <th scope="row"><%= employee.id %></th>
        <th scope="row"><%= "#{employee.first_name} #{employee.last_name}" %></th>
        <th scope="row"><%= (average_hours/60/60).truncate(3) %></th>
        <th scope="row"><%= (total_hours/60/60).truncate(3) %></th>
        <th scope="row"><%= laboral_hours %></th>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
  <td><%= link_to 'Cancel and return to reports index', store_reports_path, class: 'btn btn-primary' %></td>
</p>

app/views/stores/show.html.erb
<div class="m-5">
  <%# <a name="" id="" class="btn btn-primary" href="#" role="button">Atras</a> %>
  <h1>Stores show store</h1>
  <div class="card mt-5 p-1" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title mb-3">Store ID: <%=@store.id %></h5>
        <p>Name: <%= @store.name %></p>
        <p>Addres: <%= @store.address %></p>
    </div>
  </div>
  <p>
    <td><%= link_to 'Return to store index', stores_path, class: 'btn btn-primary my-5' %></td>
  </p>
  <h3>Store employees</h3>
  <div class="card">
    <div class="card-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Position</th>
            <th scope="col">Working</th>
            <th coolspan=3>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @employees = @store.employees %>
          <% @employees.each do |employee| %>
            <tr>
              <th scope="row"><%= employee.id %></th>
              <td><%= employee.first_name %></td>
              <td><%= employee.last_name %></td>
              <td><%= employee.email %></td>
              <td><%= employee.position %></td>
              <td><%= employee.working %></td>
              <td><%= link_to 'Show', employee_path(employee.id), class: 'btn btn-primary' %></td>
              <td><%= link_to 'Edit', edit_employee_path(employee.id), class: 'btn btn-success' %></td>
              <td><%= link_to 'Delete', employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>