config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :attendances
  resources :employees

  resources :stores
  get 'store/:id/reports', to: 'stores#reports', as: 'store_reports'
  get 'store/:id/reports/attendance_by_day', to: 'stores#reports_att_by_day', as: 'store_reports_att_by_day'
  post 'store/:id/reports/attendance_by_day/date', to: 'stores#reports_att_by_day_date',
                                                   as: 'store_reports_att_by_day_date'
  get 'store/:id/reports/absence_by_month', to: 'stores#reports_abs_by_month', as: 'store_reports_abs_by_month'
  post 'store/:id/reports/absence_by_month/date', to: 'stores#reports_abs_by_month_date',
                                                  as: 'store_reports_abs_by_month_date'
  get 'store/:id/reports/average_time_by_month', to: 'stores#reports_avg_time_by_month',
                                                 as: 'store_reports_avg_time_by_month'
  post 'store/:id/reports/average_time_by_month/date', to: 'stores#reports_avg_time_by_month_date',
                                                       as: 'store_reports_avg_time_by_month_date'

  # Session routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  # Relations
  belongs_to :store
  belongs_to :employee

  # callbacks
  before_save :check_in_registration
  before_validation :store_id_relationship

  # scope
  scope :today_attendances, -> { where(check_in: Date.today.all_day) }

  private

  def check_in_registration
    self.check_in = DateTime.now.to_s(:db)
  end

  def store_id_relationship
    @employee = Employee.find(employee_id)
    self.store_id = @employee.store_id
  end
end

app/controllers/attendances_controller.rb
# frozen_string_literal: true

# Controller for Attendances
class AttendancesController < ApplicationController
  before_action :require_admin, except: [:create]
  before_action :set_variables, only: [:create]

  def show
    @attendance = Attendance.find(params[:id])
  end

  def index
    @attendances = Attendance.all
  end

  def new
    @attendance = Attendance.new
  end

  def create
    # --------------- Check-in ---------------
    check_in if params[:commit] == 'Check-in'

    # --------------- Check-out ---------------
    checkout if params[:commit] == 'Check-out'
  end

  private

  # --------------- helpers ---------------
  def set_variables
    # Where return an array of objects, so we save the first one and thus the only one object because we have only allow to have just check_in per day
    @already_check_in = employee_today_attendance(Attendance.today_attendances)
    @attendance = Attendance.new(params.require(:attendance).permit(:employee_id, :store_id))
    @employee = Employee.find_by(id: @attendance.employee_id)
  end

  def employee_today_attendance(arr_records)
    arr_records.find { |record| record.employee_id == params[:attendance][:employee_id].to_i }
  end

  def employee_nil_or_wrong_private_number
    return 'Employee not found' if @employee.nil? || @employee.working == false

    if @employee.private_number != params[:attendance][:private_number].to_i
      'Wrong priva
      te number'
    end
  end

  # --------------- Check-in ---------------
  def check_in
    flash[:alert] = employee_nil_or_wrong_private_number || check_in_already
    flash[:notice] = check_in_register if flash[:alert].nil?
    redirect_to root_path
  end

  def check_in_already
    "You already checked in at -> '#{@already_check_in.check_in.to_s(:long)}'" if @already_check_in
  end

  def check_in_register
    "✅ Check-in register at '#{DateTime.now.to_s(:long)}'" if @attendance.save
  end

  # --------------- Check-out ---------------
  def checkout
    flash[:alert] = employee_nil_or_wrong_private_number || first_check_in_or_check_out_already
    flash[:notice] = check_out_register if flash[:alert].nil?
    redirect_to root_path
  end

  def first_check_in_or_check_out_already
    return 'You first need to check-in' if @already_check_in.nil?

    'Your assistant was already recorded' if @already_check_in.check_out
  end

  def check_out_register
    flash_notice_msg = "✅ Check-out register at '#{DateTime.now.to_s(:long)}'"
    flash_notice_msg if @already_check_in.update_columns(check_out: DateTime.now.to_s(:db))
  end
end

app/helpers/attendances_helper.rb
# frozen_string_literal: true

module AttendancesHelper
end

app/views/attendances/index.html.erb
<h1 class="my-2">Attendance Index</h1>

<p>
  <%= link_to 'Add new attendance', new_attendance_path, class: 'btn btn-primary my-3' %>
</p>

<div class="card">
  <div class="card-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Employee ID</th>
          <th scope="col">Store ID</th>
          <th scope="col">Check-in</th>
          <th scope="col">Check-out</th>
          <th coolspan=3>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |attendance| %>
          <tr>
            <th scope="row"><%= attendance.employee_id %></th>
            <td><%= attendance.store_id %></td>
            <td><%= attendance.check_in %></td>
            <td><%= attendance.check_out %></td>
            <td><%= link_to 'Show Attendance', attendance_path(attendance.id), class: 'btn btn-primary' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/attendances/new.html.erb
<div class="m-5">
  <h1>Attendance number: <%=@attendance.id %></h1>

  <% if @attendance.errors.any? %>
    <h2>The following errors preventing articles to being saved</h2>
    <ul>
      <% @attendance.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with scope: :attendance, url: attendances_path, local: true do |f| %>

    <p>
      <%= f.label :employee_id %><br/>
      <%= f.number_field :employee_id %>
    </p>
    <p>
      <%= f.label :private_number %><br/>
      <%= f.number_field :private_number %>
    </p>

    <p>
      <%= f.submit "Create new attendance" %>
    </p>

    <p>
      <td><%= link_to 'Cancel and return to attendance index', attendances_path, class: 'btn btn-primary my-3' %></td>
    </p>

  <% end %>
</div>

app/views/attendances/show.html.erb
<div class="m-5">
	<h1>Attendance ID: <%=@attendance.id %></h1>
	<div class="card mt-5 p-1" style="width: auto;">
		<div class="card-body">
			<% @data = Employee.find(@attendance.employee_id) %>
			<p>Employee: <%= (@data.first_name + ' ' + @data.last_name) if @data.nil? %> </p>
			<p>Employee ID: <%= @attendance.employee_id %></p>
			<p>Store: <%= Store.find(@attendance.store_id).name %> </p>
			<p>Store ID: <%= @attendance.store_id %></p>
			<p>Check-in: <%= @attendance.check_in %></p>
			<p>Check-out: <%= @attendance.check_out %></p>
			<table>
				<thead>
					<tr>
						<th scope="col">Actions</th>
					</tr>
				</thead>
				<tbody>
					<tr class="mt-2">
						<td><%= link_to 'Go Back', attendances_path, class: 'btn btn-secondary mr-3' %></td>
						<td><%= link_to 'View employee', employee_path(@attendance.employee_id), class: 'btn btn-primary mx-1' %></td>
						<td><%= link_to 'View Store', store_path(@attendance.store_id), class: 'btn btn-primary mx-1' %></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>